version: '3.8'

services:
  # Frontend service (React)
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: saas_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../frontend:/app
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - saas-network
    restart: unless-stopped

  # Backend service (Flask API)
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: saas_backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
    depends_on:
      - postgres
      - redis
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - DATABASE_URI=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/saas_platform
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - saas-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: saas_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=saas_platform
    networks:
      - saas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching and session management)
  redis:
    image: redis:alpine
    container_name: saas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  saas-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 