version: '3.8'

services:
  # Frontend service (React)
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: saas_frontend_prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
      - VITE_APP_TITLE=KylinKing云膜智能管理系统
      - VITE_APP_ENV=production
    depends_on:
      - backend
    networks:
      - saas-network
    restart: unless-stopped

  # Nginx (Web Server)
  nginx:
    image: nginx:alpine
    container_name: saas_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ../backend/uploads:/app/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - saas-network
    restart: unless-stopped

  # Backend service (Flask API)
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: saas_backend_prod
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DATABASE_URI=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/saas_platform
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=https://www.kylinking.com,http://www.kylinking.com
    networks:
      - saas-network
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 2 --timeout 120 wsgi:app

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: saas_postgres_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=saas_platform
    networks:
      - saas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching and session management)
  redis:
    image: redis:alpine
    container_name: saas_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  saas-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 