"""添加计算参数表

Revision ID: 2ebccce3817f
Revises: e36b01390743
Create Date: 2025-05-30 13:56:59.845336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebccce3817f'
down_revision = 'e36b01390743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False, comment='计算参数'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='显示排序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='修改人'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ink_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('option_name', sa.String(length=100), nullable=False, comment='选项名称'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='显示排序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='修改人'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_freights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False, comment='区域'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='百分比'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='显示排序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='修改人'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_life', sa.Integer(), nullable=True, comment='保质期(天)'))
        batch_op.add_column(sa.Column('inspection_standard', sa.String(length=200), nullable=True, comment='检验标准'))
        batch_op.add_column(sa.Column('quality_grade', sa.String(length=100), nullable=True, comment='质量等级'))
        batch_op.add_column(sa.Column('product_quote_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='产品报价'))
        batch_op.add_column(sa.Column('show_on_kanban', sa.Boolean(), nullable=True, comment='看板显示'))
        batch_op.add_column(sa.Column('account_subject', sa.String(length=100), nullable=True, comment='科目'))
        batch_op.add_column(sa.Column('is_consumable', sa.Boolean(), nullable=True, comment='是否耗材'))
        batch_op.add_column(sa.Column('is_recyclable', sa.Boolean(), nullable=True, comment='是否可回收'))
        batch_op.add_column(sa.Column('is_hazardous', sa.Boolean(), nullable=True, comment='是否危险品'))
        batch_op.add_column(sa.Column('is_imported', sa.Boolean(), nullable=True, comment='是否进口'))
        batch_op.add_column(sa.Column('is_customized', sa.Boolean(), nullable=True, comment='是否定制'))
        batch_op.add_column(sa.Column('is_seasonal', sa.Boolean(), nullable=True, comment='是否季节性'))
        batch_op.add_column(sa.Column('is_fragile', sa.Boolean(), nullable=True, comment='是否易碎'))
        batch_op.add_column(sa.Column('is_perishable', sa.Boolean(), nullable=True, comment='是否易腐'))
        batch_op.add_column(sa.Column('is_temperature_sensitive', sa.Boolean(), nullable=True, comment='是否温度敏感'))
        batch_op.add_column(sa.Column('is_moisture_sensitive', sa.Boolean(), nullable=True, comment='是否湿度敏感'))
        batch_op.add_column(sa.Column('is_light_sensitive', sa.Boolean(), nullable=True, comment='是否光敏感'))
        batch_op.add_column(sa.Column('requires_special_storage', sa.Boolean(), nullable=True, comment='是否需要特殊存储'))
        batch_op.add_column(sa.Column('requires_certification', sa.Boolean(), nullable=True, comment='是否需要认证'))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True, comment='显示排序'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'))
        batch_op.alter_column('material_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_comment='材料分类名称',
               existing_nullable=False)
        batch_op.alter_column('base_unit_id',
               existing_type=sa.UUID(),
               comment='基本单位ID',
               existing_comment='单位ID',
               existing_nullable=True)
        batch_op.alter_column('code_prefix',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_comment='编码前缀',
               existing_nullable=True)
        batch_op.alter_column('carton_param1',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='纸箱参数1',
               existing_nullable=True)
        batch_op.alter_column('carton_param2',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='纸箱参数2',
               existing_nullable=True)
        batch_op.alter_column('carton_param3',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='纸箱参数3',
               existing_nullable=True)
        batch_op.alter_column('carton_param4',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='纸箱参数4',
               existing_nullable=True)
        batch_op.alter_column('is_accessory',
               existing_type=sa.BOOLEAN(),
               comment='是否辅料',
               existing_comment='是否配件',
               existing_nullable=True)
        batch_op.drop_index('idx_material_categories_code')
        batch_op.drop_index('idx_material_categories_enabled')
        batch_op.drop_index('idx_material_categories_name')
        batch_op.drop_index('idx_material_categories_sort')
        batch_op.drop_index('idx_material_categories_type')
        batch_op.drop_constraint('material_categories_material_code_key', type_='unique')
        batch_op.drop_column('is_self_made')
        batch_op.drop_column('is_roll_paper')
        batch_op.drop_column('is_waste_film')
        batch_op.drop_column('no_docking')
        batch_op.drop_column('cost_object_required')
        batch_op.drop_column('is_carton')
        batch_op.drop_column('is_aluminum_foil')
        batch_op.drop_column('shelf_life_days')
        batch_op.drop_column('custom_spec')
        batch_op.drop_column('subject')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('production_error_percent')
        batch_op.drop_column('material_code')
        batch_op.drop_column('product_quote')
        batch_op.drop_column('remarks')
        batch_op.drop_column('is_solvent')
        batch_op.drop_column('is_enabled')
        batch_op.drop_column('is_glue')
        batch_op.drop_column('standard_weight_min_error')
        batch_op.drop_column('is_paper_core')
        batch_op.drop_column('is_zipper')
        batch_op.drop_column('kanban_display')
        batch_op.drop_column('warehouse_range_percent')
        batch_op.drop_column('standard_weight_max_error')
        batch_op.drop_column('is_resin')
        batch_op.drop_column('participate_cost_allocation')
        batch_op.drop_column('inspection_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='检验类型(免检/抽检/全检)'))
        batch_op.add_column(sa.Column('participate_cost_allocation', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='参与成本分配'))
        batch_op.add_column(sa.Column('is_resin', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否树脂'))
        batch_op.add_column(sa.Column('standard_weight_max_error', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='标准重量最大误差'))
        batch_op.add_column(sa.Column('warehouse_range_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='入库范围%'))
        batch_op.add_column(sa.Column('kanban_display', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='看板显示'))
        batch_op.add_column(sa.Column('is_zipper', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否拉链'))
        batch_op.add_column(sa.Column('is_paper_core', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否纸芯'))
        batch_op.add_column(sa.Column('standard_weight_min_error', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='标准重量最小误差'))
        batch_op.add_column(sa.Column('is_glue', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否胶水'))
        batch_op.add_column(sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否启用'))
        batch_op.add_column(sa.Column('is_solvent', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否溶剂'))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'))
        batch_op.add_column(sa.Column('product_quote', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True, comment='产品报价'))
        batch_op.add_column(sa.Column('material_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='材料编号(字母+8位数字)'))
        batch_op.add_column(sa.Column('production_error_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='报产允许误差%'))
        batch_op.add_column(sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True, comment='显示排序'))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='科目'))
        batch_op.add_column(sa.Column('custom_spec', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='自定规格'))
        batch_op.add_column(sa.Column('shelf_life_days', sa.INTEGER(), autoincrement=False, nullable=True, comment='保质期/天'))
        batch_op.add_column(sa.Column('is_aluminum_foil', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否铝箔'))
        batch_op.add_column(sa.Column('is_carton', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否纸箱'))
        batch_op.add_column(sa.Column('cost_object_required', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='成本对象必填'))
        batch_op.add_column(sa.Column('no_docking', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='不对接'))
        batch_op.add_column(sa.Column('is_waste_film', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否废膜'))
        batch_op.add_column(sa.Column('is_roll_paper', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否卷纸'))
        batch_op.add_column(sa.Column('is_self_made', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否自制'))
        batch_op.create_unique_constraint('material_categories_material_code_key', ['material_code'])
        batch_op.create_index('idx_material_categories_type', ['material_type'], unique=False)
        batch_op.create_index('idx_material_categories_sort', ['sort_order'], unique=False)
        batch_op.create_index('idx_material_categories_name', ['material_name'], unique=False)
        batch_op.create_index('idx_material_categories_enabled', ['is_enabled'], unique=False)
        batch_op.create_index('idx_material_categories_code', ['material_code'], unique=False)
        batch_op.alter_column('is_accessory',
               existing_type=sa.BOOLEAN(),
               comment='是否配件',
               existing_comment='是否辅料',
               existing_nullable=True)
        batch_op.alter_column('carton_param4',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_comment='纸箱参数4',
               existing_nullable=True)
        batch_op.alter_column('carton_param3',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_comment='纸箱参数3',
               existing_nullable=True)
        batch_op.alter_column('carton_param2',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_comment='纸箱参数2',
               existing_nullable=True)
        batch_op.alter_column('carton_param1',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_comment='纸箱参数1',
               existing_nullable=True)
        batch_op.alter_column('code_prefix',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_comment='编码前缀',
               existing_nullable=True)
        batch_op.alter_column('base_unit_id',
               existing_type=sa.UUID(),
               comment='单位ID',
               existing_comment='基本单位ID',
               existing_nullable=True)
        batch_op.alter_column('material_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_comment='材料分类名称',
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('display_order')
        batch_op.drop_column('requires_certification')
        batch_op.drop_column('requires_special_storage')
        batch_op.drop_column('is_light_sensitive')
        batch_op.drop_column('is_moisture_sensitive')
        batch_op.drop_column('is_temperature_sensitive')
        batch_op.drop_column('is_perishable')
        batch_op.drop_column('is_fragile')
        batch_op.drop_column('is_seasonal')
        batch_op.drop_column('is_customized')
        batch_op.drop_column('is_imported')
        batch_op.drop_column('is_hazardous')
        batch_op.drop_column('is_recyclable')
        batch_op.drop_column('is_consumable')
        batch_op.drop_column('account_subject')
        batch_op.drop_column('show_on_kanban')
        batch_op.drop_column('product_quote_price')
        batch_op.drop_column('quality_grade')
        batch_op.drop_column('inspection_standard')
        batch_op.drop_column('shelf_life')

    op.drop_table('quote_freights')
    op.drop_table('ink_options')
    op.drop_table('calculation_parameters')
    # ### end Alembic commands ###
