"""Add payment methods table

Revision ID: 404f7c3661ce
Revises: 450a5ddef985
Create Date: 2025-05-27 15:10:05.751629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404f7c3661ce'
down_revision = '450a5ddef985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_name', sa.String(length=100), nullable=False, comment='付款方式'),
    sa.Column('cash_on_delivery', sa.Boolean(), nullable=True, comment='货到付款'),
    sa.Column('monthly_settlement', sa.Boolean(), nullable=True, comment='月结'),
    sa.Column('next_month_settlement', sa.Boolean(), nullable=True, comment='次月结'),
    sa.Column('cash_on_delivery_days', sa.Integer(), nullable=True, comment='货到付款日'),
    sa.Column('monthly_settlement_days', sa.Integer(), nullable=True, comment='月结天数'),
    sa.Column('monthly_reconciliation_day', sa.Integer(), nullable=True, comment='每月对账日'),
    sa.Column('next_month_settlement_count', sa.Integer(), nullable=True, comment='次月月结数'),
    sa.Column('monthly_payment_day', sa.Integer(), nullable=True, comment='每月付款日'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='显示排序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='修改人'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
