"""添加材料分类表

Revision ID: 44febe662835
Revises: 066e39602a0b
Create Date: 2025-05-26 16:40:04.930542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44febe662835'
down_revision = '066e39602a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.String(length=20), nullable=False, comment='材料编号(字母+8位数字)'),
    sa.Column('material_name', sa.String(length=200), nullable=False, comment='材料分类名称'),
    sa.Column('material_type', sa.String(length=20), nullable=False, comment='材料属性(主材/辅材)'),
    sa.Column('base_unit_id', sa.UUID(), nullable=True, comment='单位ID'),
    sa.Column('auxiliary_unit_id', sa.UUID(), nullable=True, comment='辅助单位ID'),
    sa.Column('sales_unit_id', sa.UUID(), nullable=True, comment='销售单位ID'),
    sa.Column('density', sa.Numeric(precision=10, scale=4), nullable=True, comment='密度'),
    sa.Column('square_weight', sa.Numeric(precision=10, scale=4), nullable=True, comment='平方克重'),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True, comment='保质期/天'),
    sa.Column('inspection_type', sa.String(length=20), nullable=True, comment='检验类型(免检/抽检/全检)'),
    sa.Column('standard_weight_max_error', sa.Numeric(precision=10, scale=4), nullable=True, comment='标准重量最大误差'),
    sa.Column('standard_weight_min_error', sa.Numeric(precision=10, scale=4), nullable=True, comment='标准重量最小误差'),
    sa.Column('production_error_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='报产允许误差%'),
    sa.Column('latest_purchase_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='最近采购价'),
    sa.Column('sales_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='销售价'),
    sa.Column('product_quote', sa.Numeric(precision=15, scale=4), nullable=True, comment='产品报价'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='成本价格'),
    sa.Column('kanban_display', sa.String(length=200), nullable=True, comment='看板显示'),
    sa.Column('subject', sa.String(length=200), nullable=True, comment='科目'),
    sa.Column('code_prefix', sa.String(length=20), nullable=True, comment='编码前缀'),
    sa.Column('warning_days', sa.Integer(), nullable=True, comment='预警天数'),
    sa.Column('warehouse_range_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='入库范围%'),
    sa.Column('carton_param1', sa.Numeric(precision=10, scale=4), nullable=True, comment='纸箱参数1'),
    sa.Column('carton_param2', sa.Numeric(precision=10, scale=4), nullable=True, comment='纸箱参数2'),
    sa.Column('carton_param3', sa.Numeric(precision=10, scale=4), nullable=True, comment='纸箱参数3'),
    sa.Column('carton_param4', sa.Numeric(precision=10, scale=4), nullable=True, comment='纸箱参数4'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('enable_batch', sa.Boolean(), nullable=True, comment='启用批次'),
    sa.Column('enable_barcode', sa.Boolean(), nullable=True, comment='启用条码'),
    sa.Column('custom_spec', sa.Boolean(), nullable=True, comment='自定规格'),
    sa.Column('is_ink', sa.Boolean(), nullable=True, comment='是否油墨'),
    sa.Column('is_accessory', sa.Boolean(), nullable=True, comment='是否配件'),
    sa.Column('is_resin', sa.Boolean(), nullable=True, comment='是否树脂'),
    sa.Column('is_roll_paper', sa.Boolean(), nullable=True, comment='是否卷纸'),
    sa.Column('is_waste_film', sa.Boolean(), nullable=True, comment='是否废膜'),
    sa.Column('is_glue', sa.Boolean(), nullable=True, comment='是否胶水'),
    sa.Column('is_zipper', sa.Boolean(), nullable=True, comment='是否拉链'),
    sa.Column('is_aluminum_foil', sa.Boolean(), nullable=True, comment='是否铝箔'),
    sa.Column('is_carton', sa.Boolean(), nullable=True, comment='是否纸箱'),
    sa.Column('is_paper_core', sa.Boolean(), nullable=True, comment='是否纸芯'),
    sa.Column('is_solvent', sa.Boolean(), nullable=True, comment='是否溶剂'),
    sa.Column('is_self_made', sa.Boolean(), nullable=True, comment='是否自制'),
    sa.Column('no_docking', sa.Boolean(), nullable=True, comment='不对接'),
    sa.Column('cost_object_required', sa.Boolean(), nullable=True, comment='成本对象必填'),
    sa.Column('participate_cost_allocation', sa.Boolean(), nullable=True, comment='参与成本分配'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='显示排序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='修改人'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.create_index('idx_material_categories_code', ['material_code'], unique=False)
        batch_op.create_index('idx_material_categories_enabled', ['is_enabled'], unique=False)
        batch_op.create_index('idx_material_categories_name', ['material_name'], unique=False)
        batch_op.create_index('idx_material_categories_sort', ['sort_order'], unique=False)
        batch_op.create_index('idx_material_categories_type', ['material_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.drop_index('idx_material_categories_type')
        batch_op.drop_index('idx_material_categories_sort')
        batch_op.drop_index('idx_material_categories_name')
        batch_op.drop_index('idx_material_categories_enabled')
        batch_op.drop_index('idx_material_categories_code')

    op.drop_table('material_categories')
    # ### end Alembic commands ###
