"""添加报价辅材表

Revision ID: add_quote_accessories_table
Revises: fca5d7122e46
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_quote_accessories_table'
down_revision = 'fca5d7122e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_accessories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False, comment='租户ID'),
    sa.Column('material_name', sa.String(length=100), nullable=False, comment='材料名称'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='单价'),
    sa.Column('unit_price_formula', sa.String(length=200), nullable=True, comment='单价计算公式'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False, comment='创建人'),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True, comment='修改人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_accessories_tenant_id'), 'quote_accessories', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_accessories_tenant_id'), table_name='quote_accessories')
    op.drop_table('quote_accessories')
    # ### end Alembic commands ### 