"""添加计算方案表

Revision ID: ddc393b778ab
Revises: 2ebccce3817f
Create Date: 2025-05-30 14:34:17.607672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc393b778ab'
down_revision = '2ebccce3817f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_name', sa.String(length=100), nullable=False, comment='方案名称'),
    sa.Column('scheme_category', sa.String(length=50), nullable=False, comment='方案分类'),
    sa.Column('scheme_formula', sa.Text(), nullable=True, comment='方案公式'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='显示排序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='修改人'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scheme_category IN ('bag_spec', 'bag_formula', 'bag_quote', 'material_usage', 'material_quote', 'process_quote', 'process_loss', 'process_bonus', 'process_piece', 'process_other', 'multiple_formula')", name='calculation_schemes_category_check'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_schemes')
    # ### end Alembic commands ###
